modLoader="javafml"
loaderVersion="[1,)"
issueTrackerURL="https://github.com/Mrbysco/LiquidBlocks/issues"
license="MIT"

[[mods]]
modId="liquidblocks"
version="${file.jarVersion}"
displayName="Liquid Blocks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/liquid-blocks"
authors="Mrbysco"
description='''
Need to fill spots fast?
'''
[[dependencies.liquidblocks]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.20.4,1.21)"
ordering="NONE"
side="BOTH"
[[dependencies.liquidblocks]]
modId="neoforge"
type="REQUIRED"
versionRange="[20.4.60-beta,)"
ordering="NONE"
side="BOTH"