modLoader="javafml"
loaderVersion="[44,)"
issueTrackerURL="https://github.com/Mrbysco/LiquidBlocks/issues"
license="MIT"

[[mods]]
modId="liquidblocks"
version="${file.jarVersion}"
displayName="Liquid Blocks"
displayURL="https://www.curseforge.com/minecraft/mc-mods/liquid-blocks"
authors="Mrbysco"
description='''
Need to fill spots fast?
'''
[[dependencies.liquidblocks]]
modId="minecraft"
mandatory=true
versionRange="[1.19.3,1.20)"
ordering="NONE"
side="BOTH"
[[dependencies.liquidblocks]]
modId="forge"
mandatory=true
versionRange="[44.0.36,)"
ordering="NONE"
side="BOTH"